# Jekyll
permalink: /:categories/:title/
exclude: [release.sh]
markdown: redcarpet
name: Pallet
highlighter: pygments
domain: palletops.com
gems:
  - jekyll-redirect-from
baseurl: /
description: Pallet is a platform for agile and programmatic automation of 
   infrastructure in the cloud, on server racks or directly on virtual machines.
collections:
  pages:
    output: true
